/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lib.not.impl;

public final class LibNotImpl {
    private static final String STR = "THIS IS A STATIC STRING";

    public static String getStaticString() {
        return STR;
    }
}
