/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lib.not.impl;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibNotImplTest {
    @BeforeEach
    void setUp() {
        System.out.println("setUp() called from " + this.getClass().getCanonicalName());
    }

    @Test
    void getStaticString1() {
        Assertions.assertEquals("THIS IS A STATIC STRING", LibNotImpl.getStaticString());
    }
    @Test
    void getStaticString2() {
        Assertions.assertEquals("THIS IS A STATIC STRING", LibNotImpl.getStaticString());
    }
}
