/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package top.level.lib;

public class TopLevelLib {

    public String topLevelLibString() {
        return "String from: " + this.getClass().getCanonicalName();
    }
}
