/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.project;

import java.util.ArrayList;
import java.util.List;
import lib.api.LibApi;
import lib.impl.a.LibImplA;
import lib.impl.b.LibImplB;
import lib.not.impl.LibNotImpl;
import top.level.lib.TopLevelLib;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println("===================================");
        System.out.println(new App().getGreeting());
        System.out.println(new TopLevelLib().topLevelLibString());
        System.out.println("===================================");

        List<LibApi> impls = new ArrayList<>();
        impls.add(new LibImplA());
        impls.add(new LibImplB());

        for (LibApi impl : impls) {
            System.out.println("vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv");
            System.out.println(impl.getStr1());
            System.out.println(impl.getStr2());
            System.out.println("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
        }

        System.out.println(">>>> " + LibNotImpl.getStaticString() + " <<<<");

    }
}
